### ISSUE TITLE
update and render inverted in the Engine 

### ISSUE THREAD

**Issue by jerome649** [frankarendpoth/frankarendpoth.github.io#4]
I think update and render methods are inverted in the Engine constructor.
Shouldn't it be const Engine = function(time_step, render, update) {

**Comment by frankarendpoth** [comment]
You mean the parameters are in the wrong order? I don't think it matters what order the parameters are in so long as they get used the right way.

**Comment by jerome649** [comment]
Yes but in the rabbit trap source code the main files always contain

var engine     = new Engine(1000/30, render, update);

So I think either render and update should be switch in engine constructor or each main files should be updated.

**Comment by frankarendpoth** [comment]
I see what you mean. It is inconsistent. Unfortunately the videos are
already made and once the video is out I can't update the source code
because it wouldn't be consistent with the video. That was something I
decided going in. The lesser of two evils is to let whatever mistakes and
inconsistencies be as they are and take solace in the fact that the example
works, is logically sound, and matches the video. If the mistake is bad
enough I make another project and another video to correct it. I've even
removed entire projects. This doesn't seem quite that bad, however. Thanks
for catching that, though. Keen eye.

**Comment by frankarendpoth** [comment]
I'm going to close this issue because the code is functional albeit inconsistent across different examples in the same project.
